@startuml
class EditNoteCommand <<record>> {
    + Id : int <<get>> <<init>>
    + Description : string <<get>> <<init>>
    + ExperimentId : int? <<get>> <<init>>
    + CreatorId : int? <<get>> <<init>>
}
class "IRequest"<T> {
}
"IRequest" <|-- "<NoteDto>" EditNoteCommand
@enduml
