@startuml
class ResetPasswordUseCase {
    + ResetPasswordUseCase(mapper:IMapper, dbContext:AppDbContext, securityContext:SecurityContext)
    + <<async>> Handle(request:ResetPasswordCommand, cancellationToken:CancellationToken) : Task<ResetPasswordResult>
}
class "IRequestHandler"<T1,T2> {
}
BaseUseCase <|-- ResetPasswordUseCase
"IRequestHandler" <|-- "<ResetPasswordCommand,ResetPasswordResult>" ResetPasswordUseCase
@enduml
