@startuml
class GetNotesQuery <<record>> {
    + Id : int? <<get>> <<init>>
    + ExperimentId : int? <<get>> <<init>>
}
class "IRequest"<T> {
}
"IRequest" <|-- "<QueryResult<NoteDto>>" GetNotesQuery
@enduml
