@startuml
class GetProjectsQuery <<record>> {
    + Id : int? <<get>> <<init>>
    + Name : string? <<get>> <<init>>
}
class "IRequest"<T> {
}
"IRequest" <|-- "<QueryResult<ProjectDto>>" GetProjectsQuery
@enduml
