@startuml
class LoginCommand <<record>> {
    + Username : string <<get>> <<init>>
    + Password : string <<get>> <<init>>
}
class "IRequest"<T> {
}
"IRequest" <-- "<AuthResult>" LoginCommand
@enduml
