@startuml
class ResetPasswordCommand <<record>> {
    + UserId : int <<get>> <<init>>
    + NewPassword : string <<get>> <<init>>
}
class "IRequest"<T> {
}
"IRequest" <|-- "<ResetPasswordResult>" ResetPasswordCommand
@enduml
