@startuml
class ResetMyPasswordDto <<record>> {
    + NewPassword : string <<get>> <<init>>
}
class ResetUserPasswordDto <<record>> {
    + UserId : int <<get>> <<init>>
    + NewPassword : string <<get>> <<init>>
}
@enduml
