@startuml
!include ./ApiAssemblyMarker.puml
!include ./Program.puml
!include ./Business/IServiceCollectionExtensions.puml
!include ./Business/QueryableExtensions.puml
!include ./Business/LinqExtensions.puml
!include ./Shared/AppConfiguration.puml
!include ./Service/IServiceCollectionExtensions.puml
!include ./Data/AppDbContext.puml
!include ./Data/EFCoreExtensions.puml
!include ./Data/EntityBase.puml
!include ./Data/IDeletable.puml
!include ./Business/Contracts/EmotionReading.puml
!include ./Business/Contracts/EmotionDto.puml
!include ./Business/Contracts/AuthResult.puml
!include ./Business/Contracts/ReactionDto.puml
!include ./Business/Contracts/NoteDto.puml
!include ./Business/Contracts/ExperimentDto.puml
!include ./Business/Contracts/ProjectDto.puml
!include ./Business/Contracts/UserDto.puml
!include ./Business/Contracts/QueryResult.puml
!include ./Business/Contracts/ResetPasswordResult.puml
!include ./Business/Contracts/StimuliDto.puml
!include ./Business/Queries/GetStimuliQuery.puml
!include ./Business/Queries/GetReactionsQuery.puml
!include ./Business/Queries/GetExperimentsQuery.puml
!include ./Business/Queries/GetUsersQuery.puml
!include ./Business/Queries/GetNotesQuery.puml
!include ./Business/Queries/GetProjectsQuery.puml
!include ./Business/Queries/GetReactionEmotionsQuery.puml
!include ./Business/UseCases/BaseUseCase.puml
!include ./Shared/Security/SecurityPrincipal.puml
!include ./Shared/Security/SecurityContext.puml
!include ./Shared/Enum/EmotionType.puml
!include ./Shared/Enum/UserRole.puml
!include ./Shared/Exceptions/InvalidArgumentsExceptionBuilder.puml
!include ./Shared/Exceptions/InvalidArgumentsException.puml
!include ./Shared/Exceptions/EntityNotFoundException.puml
!include ./Shared/Exceptions/ProjectGrantPermissionException.puml
!include ./Shared/Exceptions/InvalidIdentityException.puml
!include ./Shared/Exceptions/ProjectRevokePermissionException.puml
!include ./Service/Contracts/GrantRevokeProjectPermissionDto.puml
!include ./Service/Contracts/EditExperimentDto.puml
!include ./Service/Contracts/CreateProjectDto.puml
!include ./Service/Contracts/LoginResponse.puml
!include ./Service/Contracts/UserQueryDto.puml
!include ./Service/Contracts/CreateNoteDto.puml
!include ./Service/Contracts/CreateExperimentDto.puml
!include ./Service/Contracts/EditUserDto.puml
!include ./Service/Contracts/CreateEmotionDto.puml
!include ./Service/Contracts/LoginRequest.puml
!include ./Service/Contracts/StimuliQueryDto.puml
!include ./Service/Contracts/RevokeProjectPermissionDto.puml
!include ./Service/Contracts/EditNoteDto.puml
!include ./Service/Contracts/ResetPasswordDto.puml
!include ./Service/Contracts/CreateUserDto.puml
!include ./Service/Contracts/CreateReactionDto.puml
!include ./Service/Contracts/EditProjectDto.puml
!include ./Service/Contracts/CreateStimuliDto.puml
!include ./Service/Contracts/ProjectQueryDto.puml
!include ./Service/Middlewares/ErrorHandlerMiddleware.puml
!include ./Service/Middlewares/SetSecurityPrincipalMiddleware.puml
!include ./Service/Controllers/ProjectController.puml
!include ./Service/Controllers/StimuliController.puml
!include ./Service/Controllers/UserController.puml
!include ./Service/Controllers/NoteController.puml
!include ./Service/Controllers/EmotionController.puml
!include ./Service/Controllers/ReactionController.puml
!include ./Service/Controllers/ExperimentController.puml
!include ./Service/Controllers/AuthController.puml
!include ./Data/Entities/User.puml
!include ./Data/Entities/Emotion.puml
!include ./Data/Entities/Note.puml
!include ./Data/Entities/Project.puml
!include ./Data/Entities/Reaction.puml
!include ./Data/Entities/Experiment.puml
!include ./Data/Entities/Stimuli.puml
!include ./Business/Commands/Auth/ResetPasswordCommand.puml
!include ./Business/Commands/Auth/LoginCommand.puml
!include ./Business/Commands/Experiments/EditExperimentCommand.puml
!include ./Business/Commands/Experiments/CreateExperimentCommand.puml
!include ./Business/Commands/Experiments/DeleteExperimentCommand.puml
!include ./Business/Commands/Projects/DeleteProjectCommand.puml
!include ./Business/Commands/Projects/RevokeProjectPermissionCommand.puml
!include ./Business/Commands/Projects/GrantProjectPermissionCommand.puml
!include ./Business/Commands/Projects/EditProjectCommand.puml
!include ./Business/Commands/Projects/CreateProjectCommand.puml
!include ./Business/Commands/Reactions/CreateReactionCommand.puml
!include ./Business/Commands/Reactions/DeleteReactionCommand.puml
!include ./Business/Commands/Stimuli/CreateStimuliCommand.puml
!include ./Business/Commands/Stimuli/DeleteStimuliCommand.puml
!include ./Business/Commands/Notes/EditNoteCommand.puml
!include ./Business/Commands/Notes/CreateNoteCommand.puml
!include ./Business/Commands/Notes/DeleteNoteCommand.puml
!include ./Business/Commands/Users/EditUserCommand.puml
!include ./Business/Commands/Users/DeleteUserCommand.puml
!include ./Business/Commands/Users/CreateUserCommand.puml
!include ./Business/Commands/Emotions/CreateEmotionCommand.puml
!include ./Business/UseCases/Auth/ResetPasswordUseCase.puml
!include ./Business/UseCases/Auth/LoginUseCase.puml
!include ./Business/UseCases/Experiments/DeleteExperimentUseCase.puml
!include ./Business/UseCases/Experiments/CreateExperimentUseCase.puml
!include ./Business/UseCases/Experiments/GetExperimentsUseCase.puml
!include ./Business/UseCases/Experiments/EditExperimentUseCase.puml
!include ./Business/UseCases/Projects/EditProjectUseCase.puml
!include ./Business/UseCases/Projects/CreateProjectUseCase.puml
!include ./Business/UseCases/Projects/GetProjectsUseCase.puml
!include ./Business/UseCases/Projects/GrantProjectPermissionUseCase.puml
!include ./Business/UseCases/Projects/RevokeProjectPermissionUseCase.puml
!include ./Business/UseCases/Projects/DeleteProjectUseCase.puml
!include ./Business/UseCases/Reactions/DeleteReactionUseCase.puml
!include ./Business/UseCases/Reactions/GetReactionEmotionsUseCase.puml
!include ./Business/UseCases/Reactions/GetReactionsUseCase.puml
!include ./Business/UseCases/Reactions/CreateReactionUseCase.puml
!include ./Business/UseCases/StimuliUseCases/DeleteStimuliUseCase.puml
!include ./Business/UseCases/StimuliUseCases/GetStimuliUseCase.puml
!include ./Business/UseCases/StimuliUseCases/CreateStimuliUseCase.puml
!include ./Business/UseCases/Notes/DeleteNoteUseCase.puml
!include ./Business/UseCases/Notes/GetNotesUseCase.puml
!include ./Business/UseCases/Notes/CreateNoteUseCase.puml
!include ./Business/UseCases/Notes/EditNoteUseCase.puml
!include ./Business/UseCases/Users/CreateUserUseCase.puml
!include ./Business/UseCases/Users/DeleteUserUseCase.puml
!include ./Business/UseCases/Users/GetUsersUseCase.puml
!include ./Business/UseCases/Users/EditUserUseCase.puml
!include ./Business/UseCases/Emotions/CreateEmotionUseCase.puml
@enduml
