@startuml
class ErrorHandlerMiddleware {
    + ErrorHandlerMiddleware(problemDetailsFactory:ProblemDetailsFactory)
    + <<async>> InvokeAsync(context:HttpContext, next:RequestDelegate) : Task
}
IMiddleware <|-- ErrorHandlerMiddleware
@enduml
