@startuml
class ExperimentDto <<record>> {
    + Id : int <<get>> <<init>>
    + Name : string <<get>> <<init>>
    + Description : string <<get>> <<init>>
    + ProjectId : int <<get>> <<init>>
}
@enduml
