name: Build and Deploy

on:
  push:
    branches: [ "main", "cicd" ]

jobs:
  build:
    name: Build backend
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: FaceAnalyzer.Api
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag plavy/faceanalyzer-backend:${{ github.sha }}
    - name: Push the Docker image
      run: docker push plavy/faceanalyzer-backend:${{ github.sha }}
  deploy:
    name: Deploy backend
    needs: build
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: FaceAnalyzer.Api
    environment:
      name: ${{ github.ref_name }}
      url: https://backend.faceanalyzer.plavy.me/swagger/
    env:
      KUBECONFIG: ${{ secrets.KUBE_CONFIG_AZURE }}
    steps:
    - uses: actions/checkout@v3
    - uses: azure/use-kubelogin@v1
      with:
        kubelogin-version: 'v0.0.24'
    - name: Apply the Kubernetes manifest
      run: kubectl apply -n faceanalyzer -f manifest.yaml
    - name: Set the image tag
      run: kubectl set image -n faceanalyzer deployment/faceanalyzer-backend faceanalyzer-backend=plavy/faceanalyzer-backend:${{ github.sha }}
    - name: Migrate database
      run: dotnet help
